version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: make_executable.sh
      timeout: 300
      runas: ubuntu
    - location: start.sh
      timeout: 300
      runas: ubuntu